create table Billboard_Data (
	SongID varchar,
	Performer varchar,
	Song varchar,
	duration_ms numeric,
	explicit boolean,
	danceability numeric,
	energy numeric,
	"key" numeric,
	loudness numeric,
	"mode" numeric,
	speechiness numeric,
	acousticness numeric,
	instrumentalness numeric,
	liveness numeric,
	valence numeric,
	tempo numeric,
	time_signature numeric,
	genre varchar,
	duration_m numeric,
	"Month" int,
	"Day" int,
	"Year" int,
	"Overall Peak" int,
	"Total Weeks on Chart" int,
	"Total Instances" int,
	"Top 20" int);